# Generated by Django 4.0.6 on 2022-07-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_MVT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='age',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='familiar',
            old_name='birthday',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='familiar',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='familiar',
            old_name='type',
            new_name='parentezco',
        ),
    ]
